# Generated by Django 5.0.3 on 2024-05-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claimed_for',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
